# EKS environment with Docker Hub image

# Use Docker Hub image
image:
  repository: yotaka99/todo-app
  tag: 1.0

# MongoDB storage - use EBS
mongodb:
  storage:
    storageClass: ebs-sc

# WebApp service - LoadBalancer with AWS annotations
webapp:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

# Mongo Express service - LoadBalancer with AWS annotations
mongoExpress:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

# Create EBS StorageClass
storageClass:
  enabled: true
  name: ebs-sc
  provisioner: ebs.csi.eks.amazonaws.com
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    type: gp3
    encrypted: "true"